# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_banner = QtWidgets.QLabel(self.centralwidget)
        self.label_banner.setGeometry(QtCore.QRect(10, 10, 461, 101))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.label_banner.setFont(font)
        self.label_banner.setStyleSheet("QLabel {\n"
"    color: #fff;\n"
"    background-color: #0000ff;\n"
"    border: 3px solid #0000ff;\n"
"    border-radius: 5px;\n"
"}")
        self.label_banner.setAlignment(QtCore.Qt.AlignCenter)
        self.label_banner.setObjectName("label_banner")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(110, 140, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.url.setFont(font)
        self.url.setStyleSheet("QLineEdit {\n"
"    border: 3px solid #fff;\n"
"    border-radius: 5px;\n"
"}")
        self.url.setDragEnabled(True)
        self.url.setClearButtonEnabled(True)
        self.url.setObjectName("url")
        self.text = QtWidgets.QTextEdit(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(10, 280, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text.setFont(font)
        self.text.setReadOnly(True)
        self.text.setObjectName("text")
        self.make_btn = QtWidgets.QPushButton(self.centralwidget)
        self.make_btn.setGeometry(QtCore.QRect(170, 190, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setKerning(False)
        self.make_btn.setFont(font)
        self.make_btn.setStyleSheet("QPushButton {\n"
"    color: #000;\n"
"    border: 3px solid #0000ff;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #0000ff;\n"
"    color: #fff;\n"
"}")
        self.make_btn.setObjectName("make_btn")
        self.copy_btn = QtWidgets.QPushButton(self.centralwidget)
        self.copy_btn.setGeometry(QtCore.QRect(10, 250, 75, 24))
        self.copy_btn.setStyleSheet("QPushButton {\n"
"    color: #fff;\n"
"    background-color: #0000ff;\n"
"    border: 3px solid #0000ff;\n"
"    border-radius: 5px;\n"
"}\n"
"")
        self.copy_btn.setObjectName("copy_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_banner.setText(_translate("MainWindow", "Url Shorter"))
        self.label.setText(_translate("MainWindow", "Url:"))
        self.url.setPlaceholderText(_translate("MainWindow", "Your Url..."))
        self.text.setPlaceholderText(_translate("MainWindow", "https://"))
        self.make_btn.setText(_translate("MainWindow", "Make Short Link"))
        self.copy_btn.setText(_translate("MainWindow", "Copy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
