# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 490)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QLineEdit(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(150, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.line.setFont(font)
        self.line.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.line.setDragEnabled(True)
        self.line.setClearButtonEnabled(False)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.folder_list = QtWidgets.QListWidget(self.centralwidget)
        self.folder_list.setGeometry(QtCore.QRect(20, 100, 551, 341))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.folder_list.setFont(font)
        self.folder_list.setObjectName("folder_list")
        self.choose_folder_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_folder_btn.setGeometry(QtCore.QRect(460, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.choose_folder_btn.setFont(font)
        self.choose_folder_btn.setObjectName("choose_folder_btn")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(210, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.line.setPlaceholderText(_translate("MainWindow", "Folder Path..."))
        self.label.setText(_translate("MainWindow", "Enter Folder:"))
        self.choose_folder_btn.setText(_translate("MainWindow", "Choose Folder"))
        self.start_btn.setText(_translate("MainWindow", "Make Zip"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
